# Generated by Django 4.2.1 on 2025-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh sự kiện', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=50, help_text='Số người tối đa có thể tham gia'),
        ),
    ]
