# Generated by Django 5.2.5 on 2025-08-11 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short introduction about yourself (max 500 characters)', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Not specified')], default='not_specified', help_text="User's gender", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text="Phone number must be in the format: '+84xxxxxxxxx' or '0xxxxxxxxx'", max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999' or '0999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_radius',
            field=models.FloatField(default=50.0, help_text='Search radius (km)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('away', 'Away'), ('available', 'Available for connection')], default='offline', help_text='Current status', max_length=20),
        ),
    ]
