<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-08-12 08:45
=======
# Generated by Django 4.2.1 on 2025-08-12 08:59
>>>>>>> 39d5bb044f72bb486b0fc5c706d13a8eb1d291e4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
