# Generated by Django 4.2.1 on 2025-08-12 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mission_type', models.CharField(choices=[('first_login', 'Lần đầu đăng nhập'), ('daily_login', 'Đăng nhập hàng ngày'), ('add_friend', 'Kết bạn'), ('send_message', 'Gửi tin nhắn'), ('create_post', 'Tạo bài viết'), ('like_post', 'Thích bài viết'), ('comment_post', 'Bình luận bài viết'), ('share_post', 'Chia sẻ bài viết'), ('complete_profile', 'Hoàn thiện hồ sơ'), ('upload_avatar', 'Tải ảnh đại diện'), ('join_event', 'Tham gia sự kiện'), ('create_event', 'Tạo sự kiện'), ('streak_login', 'Đăng nhập liên tiếp'), ('level_up', 'Lên cấp'), ('earn_points', 'Tích lũy điểm')], max_length=20)),
                ('target_count', models.IntegerField(default=1, help_text='Số lần cần thực hiện')),
                ('points_reward', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Một lần'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng')], default='once', max_length=10)),
                ('icon', models.CharField(default='🎯', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', 'points_reward'],
            },
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('claimed', 'Đã nhận thưởng')], default='in_progress', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
