# Generated by Django 4.2.1 on 2025-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_mission_alter_userpoints_user_usermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='action',
            field=models.CharField(choices=[('login', 'Daily Login'), ('event_create', 'Create Event'), ('event_join', 'Join Event'), ('friend_add', 'Add Friend'), ('message_send', 'Send Message'), ('profile_complete', 'Complete Profile'), ('mission_complete', 'Complete Mission'), ('post_create', 'Create Post'), ('post_like', 'Like Post'), ('post_comment', 'Comment Post'), ('avatar_upload', 'Upload Avatar')], max_length=30),
        ),
    ]
